FROM        alpine:3.12

RUN         apk --update --no-cache add nginx
RUN         mkdir -p /run/nginx; mkdir -p /var/www

RUN         apk --update --no-cache add php7 php7-fpm php7-mbstring php7-session \
            php7-common php7-iconv php7-json php7-gd php7-curl php7-xml php7-mysqli php7-imap \
            php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt \
            php7-gettext php7-ldap php7-ctype php7-dom

COPY        /srcs/phpMyAdmin-5.0.2.tar.gz /
COPY	    /srcs/default.conf /etc/nginx/conf.d/
COPY	    /srcs/start.sh /

EXPOSE      5000
ENTRYPOINT  ["sh", "start.sh"]